language: swift

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone X'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GPVideoPlayer.xcworkspace -scheme GPVideoPlayer-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty



